// Developer Express Code Central Example:
// How to define bars and bar items via a template
// 
// This example shows how to define a bar, bar items and bar item links in a
// DataTemplate, and then use this template to create these objects in a
// BarManager. Bar objects are defined via the DataTemplate class. The
// DataTemplate's content must be a BarManagerActionContainer object, containing
// actions to create bar objects. The created template is used within the
// BarManager via the BarManager.Controllers collection.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E1731

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarManagerControllerExample.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
